### ISSUE TITLE
[CRITICAL] HTTP Error 429/503

### ISSUE THREAD

**Issue by George-Martinec** [22XploiterCrew-Team/WordPress-Brute-Force#4]
`[CRITICAL] HTTP Error 429: Too Many Requests.` / `[CRITICAL] HTTP Error 503: Service Unavailable`

Python Version: **3.9.6**

Code:
`python WpCrack.py -t https://www.TEST_WEB.com/ -u admin --p wordlist.txt -d`

Any tips how to make it work ?

**Comment by RandsX** [comment]
have you tried on different sites? and is the result the same?

**Comment by George-Martinec** [comment]
Some websites have IP limitations, I would recommend using IP Rotator using for example Tor.

**Comment by RandsX** [comment]
yes, in this second version I will develop again about this problem and other features. My laptop is broken now.
